apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: a-messages
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: a_messages
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    min.insync.replicas: 2